#!/bin/bash

# Installer for mipman

echo ' Installing...'

# Install mipnote script
sudo cp mipnote /usr/bin/mipnote

# Edit config file
. mipnote.conf

echo ' Would you like to edit the config file?'
read -p ' E.g: If you want to change notes directory - default location is ~/Documents/mipnote_notes/ [y/n]? ' response
if [ "${response,,}" == "y" ] || [ "${response,,}" == "yes" ] ; then
		nano mipnote.conf
fi

# Create and initialises notes directory + Git repository
if [[ -d "${notes_dir}" ]] ; then
		read -p '  Notes directory already exists, continuing will erase it and all the notes inside [y/n]? ' response
		if [ "${response,,}" == "y" ] || [ "${response,,}" == "yes" ] ; then
				rm -r "${notes_dir}"
				mkdir "${notes_dir}"
                git init "${notes_dir}"


				unset response
		fi
else
		mkdir "${notes_dir}"
		git init "${notes_dir}"
fi

# Create config
cp mipnote.conf "${XDG_CONFIG_HOME}"

(($? != 0)) && { printf '%s\n' " An error occured in installation"; exit 1; }

echo ' Installation was successful! Go edit some notes :)'
