#!/bin/bash

# Installer for mipman

echo ' Installing...'

# Install mipnote script
cp mipnote /usr/bin/mipnote

# Edit config file
. mipnote.conf

echo ' Would you like to change the config file?'
read -p ' E.g: The notes directory default location is ~/Documents/mipnote_notes/ [y/n]? ' response
if [ "${response,,}" == "y" ] || [ "${response,,}" == "yes" ] ; then
		nano mipnote.conf
fi

# Create and initialises notes directory + Git repository
./mipnote -i

# Create config
cp mipnote.conf ${XDG_CONFIG_HOME}

(($? != 0)) && { printf '%s\n' " An error occured in installation"; exit 1; }

echo ' Installation was successful!'
